# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  environment = { BASE_URL = "http://localhost:3000", GOOGLE_API_SEARCH_KEY = "AIzaSyCLQ7UaeqF98kReGcRAyqjqCR_aCEZjb28", GOOGLE_API_SEED = "005908673950574329597:la4qlpykhxi", API_COUNT_RESULTS = "1" }